const imagePath = '../../assets/images';

export const appImages = {
  img_lightOnboarding1: require(`${imagePath}/img_onboarding1(Light).png`),
  img_lightOnboarding2: require(`${imagePath}/img_onboarding2(Light).png`),
  img_lightOnboarding3: require(`${imagePath}/img_onboarding3(Light).png`),
  img_lightOnboarding4: require(`${imagePath}/img_onboarding4(Light).png`),
  img_darkOnboarding1: require(`${imagePath}/img_onboarding1(Dark).png`),
  img_darkOnboarding2: require(`${imagePath}/img_onboarding2(Dark).png`),
  img_darkOnboarding3: require(`${imagePath}/img_onboarding3(Dark).png`),
  img_darkOnboarding4: require(`${imagePath}/img_onboarding4(Dark).png`),
  img_authCard: require(`${imagePath}/img_authCard.png`),
  img_defaultProfile: require(`${imagePath}/img_defaultProfile.png`),
  img_freeUser: require(`${imagePath}/img_freeUser.png`),
  img_proUser: require(`${imagePath}/img_proUser.png`),
  img_lightHelp: require(`${imagePath}/img_lightHelp.png`),
  img_darkHelp: require(`${imagePath}/img_darkHelp.png`),
  img_test1: require(`${imagePath}/img_test1.png`),
  img_askAi: require(`${imagePath}/img_askAi.png`),
  img_user1: require(`${imagePath}/img_user1.png`),
  img_user2: require(`${imagePath}/img_user2.png`),
  img_user3: require(`${imagePath}/img_user3.png`),
  img_user4: require(`${imagePath}/img_user4.png`),
  img_user5: require(`${imagePath}/img_user5.png`),
  img_noChat: require(`${imagePath}/img_noChat.webp`),
  img_noNotification: require(`${imagePath}/img_noNotification.png`),
  img_noHistory: require(`${imagePath}/img_noHistory.png`),
  img_noWorkshop: require(`${imagePath}/img_noWorkshop.jpg`),
  img_contactSupport: require(`${imagePath}/img_contactSupport.png`),
};
