export const appText = {
  next: 'Next',
  skip: 'Skip',
  getStarted: 'Get Started',
  welcomeBack: 'Welcome back!',
  logInLine: 'Login to continue, your bookings are waiting.',
  continueWith: 'or continue with',
  dontHaveAccount: 'Don’t have an account? ',
  signUp: 'Sign Up',
  alreadyHaveAccount: 'Already have an account? ',
  logIn: 'Login',
  letsDiveIn: "Let's dive in!",
  signUpLine: 'Sign up to get started.',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot Password? ',
  reset: 'Reset',
  agreeTo: 'I agree to the ',
  and: 'and ',
  report: 'Report',
  markasDone: 'Mark as Done',
  pro: 'Pro',
  loading: 'Loading...',
  help: 'HELP',
  subscribeNow: 'Subscribe Now',
  benefits: 'BENEFITS',
  upcomingWorkshops: 'UPCOMING WORKSHOPS',
  invalidCredentials: 'Invalid Credentials',
  pleaseLogIn: 'Please Log In again',
  privacyPolicy: 'Privacy Policy ',
  terms: 'Terms of Service ',
  termsOfUse: 'Terms Of Use',
  kyoraIQ: 'Kyora IQ',
  monthly: 'MONTHLY',
  d99: '$99',
  perMo: '/mo',
  payNow: 'Pay Now',
  restore: 'Restore',
  gotIt: 'Got it!',
  delete: 'Delete',
  cancel: 'Cancel',
  unlockExpertLedWorkshops: 'Unlock Expert-Led Workshops',
  threatDetectionCareerGrowthToolsMore:
    'Threat Detection, Career Growth, Tools & more',
  realTimeQAwithExperts: 'Real-time Q&A with experts',
  workshopsEveryMondayThroughSaturday:
    'Workshops every Monday through Saturday',
  trustedby50kUsers: 'Trusted by 50k+ Users',
  pleaseTryAgain: 'Please Try Again',
  pleaseTryAgainLater: 'Please Try Again Later',
  somethingWentWrong: 'Something Went Wrong',
  pageNotFound: 'Page Not Found',
  enterValidValue: 'Please Enter valid value',
  internalServerError: 'Internal Server Error',
  invalidEmail: 'Invalid Email',
  toMayRequest: 'To Many Request',
  invalidPassword: 'Invalid Password',
  passwordLength: 'Password Must be 8 characters long.',
  mustHaveCapitalValue: 'Password Must have least 1 capital latter',
  mustHaveSmallValue: 'Password Must have least 1 small latter',
  mustHaveNumber: 'Password Must have least 1 Number',
  mustHaveSpecialChar: 'Password must have 1 special character',
  noConsultantFound: 'No Consultant named',
  noServiceFound: 'No Service named',
  found: ' Found',
  areYouSure: 'Are You Sure?',
  logoutConfirm:
    'Are you sure you want to Logout? You will need to enter your credantial to log in again.',
  deleteConfirm:
    "Are you sure you want delete your account? This action can't be undone and you will lose all your data.",
  noHistory: 'No Bookings yet',
  noChatHistory: 'No Chats!',
  notifications: 'Notifications',
  noNotification: 'no new Notification',
  bookingConfirmed: 'Booking Confirmed!',
  kyoraBot: 'KyoraBot',
  walletBalance: 'Wallet Balance',
  consultantWillReachOutToYouViaInAppChat:
    'Consultant will reach out to you via in-app chat',
  forgotPasswordLine:
    'No worries! Just enter your email, and we’ll help you reset your password.',
  sendNow: 'Send Now',
  chooseYourRole: 'Choose Your Role',
  chooseYourRoleSubTitle: "Tell us how you'd like to use the app.",
  client: 'Client',
  clientLine: 'I am looking for service',
  consultant: 'Consultant',
  consultantLine: 'I am service provider',
  continue: 'Continue',
  noWorkshop: 'no Workshop scheduled',
  completeProfile: 'Complete Your Profile',
  completeProfileLine: 'Upload a profile picture and your name to get started',
  uploadPhoto: 'Upload Photo',
  name: 'Name',
  about: 'About',
  ratingsandReviews: 'Ratings & Reviews',
  submit: 'Submit',
  userNameWarnig: 'Please enter name',
  home: 'Home',
  chat: 'Chat',
  changePhoto: 'Change Photo',
  history: 'History',
  updateProfile: 'Update Profile',
  profile: 'Profile',
  searchPlaceHolder: 'Search “Cloud Security”',
  bookingHistory: 'Booking History',
  viewAll: 'View All',
  browseServices: 'Browse Services',
  workshop: 'Workshops',
  addToCalander: 'Add to Calender',
  tellUsMore: 'Tell us more',
  shareYourThoughts: 'Share your thoughts',
  yourExpertise: 'What’s Your Expertise?',
  yourExpertiseLine: 'Select categories that best represents your work',
  addYourServices: 'Add Your Services',
  addYourServicesLine: 'Help clients discover your key offerings',
  addService: 'Add Service',
  bookNow: 'Book Now',
  addPersonalDetails: 'Add Personal Details',
  addPersonalDetailsLine: 'Tell clients who you are',
  yearsOfExperience: 'Years of Experience',
  bio: 'Bio',
  pendingVerification: 'Pending Verification',
  yourRating: 'Your Rating',
  shareYourExperience: 'Share Your Experience',
  pendingVerificationLine:
    'Your profile is currently under review by our team. You’ll receive an email with the next steps shortly.',
  searchConsultants: 'Search Consultants',
  searchClients: 'Search Clients',
  bookingId: 'Booking ID',
  message: 'Message',
  sendMessage: 'Send a message...',
  appearance: 'Appearance',
  changePassword: 'Change Password',
  general: 'GENERAL',
  contactSupport: 'Contact Support',
  aboutUs: 'About Us',
  downloadInvoice: 'Download Invoice',
  rateYourExperience: 'Rate Your Experience',
  termsPrivacy: 'Terms & Privacy',
  account: 'ACCOUNT',
  deleteAccount: 'Delete Account',
  askDeleteAccount: 'Delete Account?',
  logout: 'Logout',
  askLogout: 'Logout?',
  version: 'V 1.0.1',
  expertise: 'Expertise & Services',
  editProfile: 'Edit Profile',
  savePreference: 'Save Preference',
  lightTheme: 'Light Theme',
  darkTheme: 'Dark Theme',
  deviceTheme: 'Device Theme',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  updatePassword: 'Update Password',
  bookingSummary: 'Booking Summary',
  bookingDetails: 'Booking Details',
  billDetails: 'BILL DETAILS',
  hourlyRate: 'Hourly Rate',
  hoursBooked: 'Hours Booked',
  total: 'Total',
  platformFee: 'Platform Fee',
  tax: 'Tax & Charges',
  grandTotal: 'Grand Total',
  terrible: 'Terrible',
  bad: 'Bad',
  okay: 'Okay',
  good: 'Good',
  excellent: 'Excellent',
  expertiseAndServices: 'Expertise & Services',
  serviceConsultant: 'Service & Consultant',
};

export const tourText: { [key: number]: string } = {
  1: 'This is your Profile.',
  2: 'You can Browse Services here.',
  3: 'This is your home page.',
  4: 'You can chat with other people here.',
  5: 'This is your booking history.',
  6: 'This is your profile screen.',
};
