export const endPoints = {
  feedBackRefine: 'feedback-refine',
  askChatbot: 'ask-chatbot',
  expertise: 'expertises',
  consultantList: 'consultants-list',
  clientProfile: 'client-profile',
  billCount: 'bookings/bill-count',
  consultant: 'consultants',
  chatHistory: 'chat-history',
  clientHome: 'client-home',
  consultantProfile: 'consultant-profile',
  workshopList: 'workshops-list',
  booking: 'bookings',
  notification: 'notifications',
  logIn: 'login',
  consultantProfileSetup: 'consultant-profile-setup',
  consultantVerified: 'consultant-verified',
  consultantHome: 'consultant-home',
  ratingReviews: 'rating-reviews',
  plans: 'plans',
  bookingComplete: 'bookings-complete',
  invoice: 'bookings/invoice',
  consultantExpertises: 'consultant-expertises',
  consultantServices: 'consultant-services',
};
